### ISSUE TITLE
Version 1.2.0 does not run module after successful built

### ISSUE THREAD

**Issue by sebi06** [apeer-micro/apeer-module-debugger#25]
* Download and install release 1.2.0
* Build the module:

![image](https://user-images.githubusercontent.com/3833249/88546419-a4287d00-d01c-11ea-93b0-88ae624b6efd.png)

* Select Input File, Modify parameters and press **RUN** --> nothing happens, no error messages etc.

![image](https://user-images.githubusercontent.com/3833249/88546547-d6d27580-d01c-11ea-9dcf-8e4670455cd5.png)

**Comment by nitish-tripathi** [comment]
@sebi06 can you share module with me?

**Comment by miura** [comment]
I have the same problem

**Comment by nitish-tripathi** [comment]
@sebi06 @miura can you guys please download 1.4.0 and check whether the issue is solved? Thank you.
