### ISSUE TITLE
Build Notification appears in front of Run button

### ISSUE THREAD

**Issue by guiherzog** [apeer-micro/apeer-module-debugger#8]
Every time I build something, it shows the notification balloon in front of the "Run" button. This makes me unable to quickly switch from Build to Run as I have to wait the notification to disappear. 

Ideally, it would show the notification in another area on the screen.

Thanks :)

**Comment by nitish-tripathi** [comment]
yeah, I know. The first priority was to finish first version in a good enough package. But thanks for opening the issue. I will try to fix it

**Comment by nitish-tripathi** [comment]
The issue with the referenced pr
